apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: sahayak
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db